---
services:
  ai_generator:
    build: .
    environment:
      - GROQ_API_KEY: "${GROQ_API_KEY}"

    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./schema:/app/schema

    restart: unless-stopped
